name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: archspec
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.41.0  # MSRV
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test
      
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
